### ISSUE TITLE
fyi: api changes in zig master

### ISSUE THREAD

**Issue by bradclawsie** [vrischmann/zig-sqlite#67]
I completely understand if you wish to only track the latest stable release...nonetheless, here is some information regarding breaking changes on zig master:

```
$ zig version                                                                                      
0.9.0-dev.1896+a1b79ea58
```

trying to build some code using this lib:

```
/home/brad/.zig/zig-linux-x86_64-0.9.0-dev.1896+a1b79ea58/lib/std/mem.zig:664:19: error: deprecated; use use std.mem.span() or std.mem.sliceTo()                                                      pub const spanZ = @compileError("deprecated; use use std.mem.span() or std.mem.sliceTo()");                          ^                                                                                ./.zigmod/deps/git/github.com/vrischmann/zig-sqlite/sqlite.zig:289:27: note: referenced here                   break :blk mem.spanZ(msg);                                                                                       ^
```

thanks for making this library, I don't think I would have bothered with zig without it
Brad

**Comment by vrischmann** [comment]
Hi,

I only track zig master :) I pushed the fixes today.

Usually I prepare the fixes in advance in a branch and wait until the [tarball](https://ziglang.org/download/) is up to date, otherwise the CI will fail. In this case the tarball wasn't updated for 4/5 days so it took a while to merge.

It's not strictly required to do it this way but that's just my preference.

Thanks for the heads up though !

**Comment by vrischmann** [comment]
Oh and glad you enjoy the library !
